local QBCore = exports['qb-core']:GetCoreObject()

QBCore.Functions.CreateCallback('azqb-displayid:server:getPlayerServerId', function(source, cb)
    return cb(source)
end)

QBCore.Functions.CreateCallback('azqb-displayid:server:getTime', function(source, cb)
    local timestamp = os.time()
    local mon = tonumber(os.date("%m", timestamp))
    local day = tonumber(os.date("%d", timestamp))
    local hour = tonumber(os.date("%H", timestamp))
    local min = tonumber(os.date("%M", timestamp))
    local sec = tonumber(os.date("%S", timestamp))
    -- os.date("%m/%d %H:%M:%S")
    return cb(mon, day, hour, min, sec)
end)